// layout.js - Keep as is, no changes needed
import { Inria_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inriaSans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inria-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inriaSans.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
